version: "3.8"

services:
  traefik:
    image: traefik:v2.11
    command:
      - "--api.insecure=true"  # pouze pro vývoj, později vypnout!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=jiri.medved@konzult.net"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    networks:
      - traefik

  backend:
    image: ghcr.io/jirmed/todo-backend:latest
    expose:
      - "18080"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todo-backend.rule=Host(`todo.konzult.net`) && PathPrefix(`/api`)"
      - "traefik.http.routers.todo-backend.entrypoints=websecure"
      - "traefik.http.routers.todo-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.todo-backend.loadbalancer.server.port=18080"

  frontend:
    image: ghcr.io/jirmed/todo-frontend:latest
    expose:
      - "80"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todo-frontend.rule=Host(`todo.konzult.net`)"
      - "traefik.http.routers.todo-frontend.entrypoints=websecure"
      - "traefik.http.routers.todo-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.todo-frontend.loadbalancer.server.port=80"
# Tento soubor je shodný s docker-compose.local.yaml
# Pro lokální vývoj stačí použít příkaz: docker compose up

version: "3.8"

services:
  traefik:
    image: traefik:v2.11
    command:
      - "--api.insecure=true"  # pouze pro vývoj
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Dashboard pro traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`localhost`) && (PathPrefix(`/api/dashboard`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"

  backend:
    image: ghcr.io/jirmed/todo-backend:latest
    expose:
      - "18080"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todo-backend.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.todo-backend.entrypoints=web"
      - "traefik.http.services.todo-backend.loadbalancer.server.port=18080"

  frontend:
    image: ghcr.io/jirmed/todo-frontend:latest
    expose:
      - "80"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todo-frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.todo-frontend.entrypoints=web"
      - "traefik.http.services.todo-frontend.loadbalancer.server.port=80"

networks:
  traefik:
volumes:
  letsencrypt:

networks:
  traefik:
    external: true
