version: "3.8"

services:
  traefik:
    image: traefik:v2.11
    command:
      # společná konfigurace pro všechny scénáře
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks: [traefik]
    labels:
      - "traefik.enable=true"   # detailní routy doplní overrides

  backend:
    image: ghcr.io/jirmed/todo-backend:latest
    expose: ["18080"]
    networks: [traefik]
    labels: ["traefik.enable=true"]  # routy + TLS doplní overrides

  frontend:
    image: ghcr.io/jirmed/todo-frontend:latest
    expose: ["80"]
    networks: [traefik]
    labels: ["traefik.enable=true"]  # routy + TLS doplní overrides

networks:
  traefik:

volumes:
  letsencrypt:   # používá pouze produkční varianta
