version: "3.8"

services:
  traefik:
    image: traefik:v2.11
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik
version: "3.8"

services:
  traefik:
    image: traefik:v2.11
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Dashboard pro traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`localhost`) && (PathPrefix(`/api/dashboard`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "18080"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todo-backend.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.todo-backend.entrypoints=web"
      - "traefik.http.services.todo-backend.loadbalancer.server.port=18080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "80"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todo-frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.todo-frontend.entrypoints=web"
      - "traefik.http.services.todo-frontend.loadbalancer.server.port=80"

networks:
  traefik:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "18080"
    volumes:
      - "./backend/src:/app/src:ro"  # Pro rychlejší development
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todo-backend.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.todo-backend.entrypoints=web"
      - "traefik.http.services.todo-backend.loadbalancer.server.port=18080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "80"
    volumes:
      - "./frontend:/app:ro"  # Pro rychlejší development
      - "/app/node_modules"  # Vyloučit node_modules z volumes
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todo-frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.todo-frontend.entrypoints=web"
      - "traefik.http.services.todo-frontend.loadbalancer.server.port=80"

networks:
  traefik:
