version: "3.8"

services:
  backend:
    image: ghcr.io/jirmed/todo-backend:latest
    expose:
      - "18080"
    restart: unless-stopped

  frontend:
    image: ghcr.io/jirmed/todo-frontend:latest
    expose:
      - "80"
    restart: unless-stopped

  proxy:
    image: ghcr.io/jirmed/todo-proxy:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
