name: CI Backend Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image (ARM64)
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: false
          platforms: linux/arm64
